### ISSUE TITLE
V3 Redesign

### ISSUE THREAD

**Issue by asim** [m3o/dev#269]
## Design for V3

A few of the goals in relation to shipping v3 of micro and go-micro

## Overview

Micro v3 is a departure from our previous experiences. We want to transition go-micro to be the purely open source distributed systems library and for micro itself to be the all encompassing framework and platform like experience. Micro should provide a rails like experience and give you a development environment (locally or hosted) along with the libraries needed to write code. You should continue to be able to run micro locally but also seamlessly transition to a self hosted server or our platform. Go-micro should remain a pure open source library.

## Design

From a design perspective we firstly want to transition go-micro into just a pure open source library which we use as a standard library for distributed systems development and less of a framework. We want to move micro itself to being the framework. Why? The complexity of a framework coinciding with our platform work makes it difficult to do this split between two projects but also harder as a library. By cleanly separating the responsibilities we resolve these issues, provide a foundational library on top of Go for distributed systems and the next level experience with micro as a framework and platform. We also know that Go adoption primarily comes down to idiomatic library usage and so pushing go-micro in this direction feels like turning it into a useful utility.

## Goals

How do we look to achieve this? By stripping from go-micro some of the complexity and moving it to micro but also clearing up some of the confusion in our tooling e.g if you want to run a service using micro locally or on the platform it must import github.com/micro/micro/service. If you want to use services such as the registry, broker, store, etc it must be through a github.com/micro/micro/service/{broker, registry, store, ...} import which is initialised to use the service layer. Go-micro has a list of plugin packages to choose from and this can be confusing for users. Its fine for open source where you want to pick and choose your underlying infrastructure but micro as a platform should eliminate that choice and focus on the service layer.

Additionally this service layer does not need to be built as interfaces. It can likely make use of go-micro internally but provide a user friendlier experience on top but should also be initialised by default to let users get on with writing code.

## Architecture

For go-micro, our expectation is to strip top level NewService and stick with the individual packages, along with removing config/cmd for env var and flag parsing so people can use any flag parsing they want.

For micro, we want the experience to start with the `micro server` which encapsulates the requirements for distributed systems development. Details can be found [here](https://github.com/micro/micro). Once a server is running the next step is to create a new service using `micro new [service]` which should create a directory structure for your service and any surrounding api, web, cli client requirements. Api, cli, web, bot and proxy are our clients for accessing services and we expect that we want to augment them to indicate how we want clients to access services but primarily we want to have one form of service development, a "micro" service. In past we had different types, but this we're now going to do away with in favour of auto generated clients for each concern. In the case of web, we'll provide a go-micro/web utility and micro/web layer that lets you define single page apps or SPA thats very rudimentary.

## Outcome

- Go Micro becomes a standard library for distributed systems
- Go Micro remains purely open source and requires explicit choice of plugin use
- Micro becomes a framework and cloud native development platform
- Micro requires use of the service layer instead of choosing plugins
- Micro drives a new kind of developer experience

## TODO

- [x] Move env var / flag parsing (config/cmd) into micro/micro
- [x] Move complex service initialisation to import "github.com/micro/micro/service" and service.New()
- [x] Move all "service" implementations of plugins into micro/micro/service
- [x] Move to importing only micro/micro/service for service.New()
- [x] Initialise `micro new` templates using "github.com/micro/micro/service"
- [x] `micro env set local` as being the local server (requiring micro server)
- [x] Execute all commands against local server by default
- [x] Operate in a cloud first platform model

**Comment by crufter** [comment]
> Operate in a cloud first platform model
Could you elaborate on this please?

**Comment by asim** [comment]
Operate in a cloud first model basically means assume you're default environment is the platform and all your actions are platform first rather than local first. Which might mean we explicitly make platform the default rather than local.

**Comment by hhstore** [comment]
- if `v3` is coming, so, is `go-micro v2` a temporary version? 
- and will not use for long-term maintenance? 
- also should not be use for production environment ?
- what is the best choice at this moment? 
- go-micro v1 ? or  v2 some specific version, like `v2.9.1` ?
- i just use `go-micro v2.9.1` write some commercial projects. is this a bad choice? 
- or go back to use `go-micro v1`?
- waiting for your reply, thanks.

**Comment by asim** [comment]
- v2 was a transition. People wanted grpc by default so we gave it to them. After 5 years of micro and go-micro we feel v3 needs to be different. 
- we don't support past versions because of the overhead of maintenance, we bug fix where needed, but the api remains unchanged after we move
- you can use v2 for production, many do
- use v2 if you want to use go-micro as a framework with grpc
- go-micro v2.9.1 is fine for commercial use
- do not go back to v1

**Comment by domwong** [comment]
If we're moving `service.New()` to be for the `micro` experience it'll be good to understand what `go-micro` users will be expected to do.

**Comment by asim** [comment]
Current go-micro users could move to using the [go-micro/service](https://github.com/micro/go-micro/tree/master/service) package. We'd keep this interface and move our top level implementation from go-micro/service.go to micro since it has complex initialisation and calling of services to get config, generate an account, etc.

Key thing to note. Existing go-micro users wanted a simple microservice development experience, not the stuff we've started to add thats dependent on the micro server. So to preserve that, it makes sense to move into the standard library model and push the service interface into its own package, while stripping the complex parts, including the flag/env var loading. For anyone who wants to preserve a v1 or v2 experience, those releases are still there for them to use. 

Otherwise I think most will be happy to manage their own flags/env vars or move to micro for a more complete rails like experience.

**Comment by hhstore** [comment]
> * v2 was a transition. People wanted grpc by default so we gave it to them. After 5 years of micro and go-micro we feel v3 needs to be different.
> * we don't support past versions because of the overhead of maintenance, we bug fix where needed, but the api remains unchanged after we move
> * you can use v2 for production, many do
> * use v2 if you want to use go-micro as a framework with grpc
> * go-micro v2.9.1 is fine for commercial use
> * do not go back to v1


- thank you for your reply.
- since using `v2.9.1`, i find `master branch` has a lot of changes from it, so It makes me confused.
- now i got it.
- `grpc` by default is fine for us. we use `grpc` and `protobuf` a lot.
- i also find a lot things move from `go-micro` to `micro` project. then `go-micro` should be clearer to the users.  
- i like `go-micro` very much.  thanks again.

**Comment by sadwxqezc** [comment]
I assume in the future new "service" implementations of plugins will first be introduced in go-micro,  then to micro, am i correct?

**Comment by asim** [comment]
No, service implementations will all be moved to micro and only live in micro. 

For all intents and purposes go-micro is a standalone Go library for distributed systems development and we build on this in micro but based on our experiences now, we need to consolidate somewhat in how we operate. Leaving pure OSS things in go-micro and focusing on our service based implementations in micro.

**Comment by asim** [comment]
Closing, the redesign is basically complete.
